config/routes.rb
ConferenceService::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "user_registrations"}
  resources :registrations, only: [:index, :create, :destroy]
  resources :speakers
  resources :events
  
  root 'events#index'
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true
  has_and_belongs_to_many :speakers
  has_many :registrations, dependent: :destroy
  has_many :users, through: :registrations
  belongs_to :timeslot
  
  validates :timeslot, presence: true
  
  def overlaps?(other)
    self.timeslot.overlaps?(other.timeslot)
  end
  
  def speaker
    self.speakers.join(", ")
  end
  
  def speaker_id
    self.speakers.first.try(:id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :require_admin!, except: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.order("timeslot_id asc")
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @available_prios = [1, 2, 3]
    if user_signed_in?
      @reg = current_user.registrations.where(event_id: @event.id).first
      other_regs = current_user.registrations.joins(:event).where("events.timeslot_id = ?", @event.timeslot.id)
      @available_prios = @available_prios - other_regs.map(&:priority)
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.speakers = [Speaker.find(params[:event][:speaker_id])] unless params[:event][:speaker_id].blank?

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        new_speaker = Speaker.find(params[:event][:speaker_id])
        @event.speakers << new_speaker unless params[:event][:speaker_id].blank? && @event.speakers.include?(new_speaker)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_time, :end_time, :description, :image_url, :location, :location_url, :timeslot_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, html: {class: "pure-form pure-form-aligned"}) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="pure-control-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="pure-control-group">
    <%= f.label :speakers %>
    <%= f.select :speaker_id, Speaker.all.map {|s| [s.name, s.id]}, include_blank: true %><br><small>(Für mehrere Workshopleiter Workshop bitte im <%= link_to "Admin", rails_admin.index_path('event') %> anlegen/bearbeiten.)</small>
  </div>

  <div class="pure-control-group">
    <%= f.label :timeslot %>
    <%= f.select :timeslot_id, Timeslot.all.map {|s| [s.name, s.id]}, include_blank: false %>
  </div>
  <!-- <div class="pure-control-group">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="pure-control-group">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div> -->
  <div class="pure-control-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="pure-control-group">
    <%= f.label :image_url %>
    <%= f.url_field :image_url %>
  </div>
  <div class="pure-control-group">
    <%= f.label :location %>
    <%= f.text_area :location %>
  </div>
  <div class="pure-control-group">
    <%= f.label :location_url %>
    <%= f.url_field :location_url %>
  </div>
  <div class="actions">
    <%= f.submit class: "pure-button pure-button-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Workshop ändern</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @event %> |
<%= link_to 'Zurück', events_path %>

app/views/events/index.html.erb
<h1>Events/Workshops <small>(<%= @events.count %>)</small></h1>

<table class="pure-table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Timeslot</th>
      <th>Beschreibung</th>
      <th>Ort</th>
      <% if current_user.try(:admin) %>
		<th></th>
      	<th></th>
	  <% end %>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= image_tag event.image_url, size: "50x50" unless event.image_url.blank? %></td>
        <td><%= link_to event.name, event %></td>
        <td><%= event.timeslot.try(:name) %><br><small>(<%= l event.timeslot.start_time, format: :short %> bis <%= l event.timeslot.end_time, format: :short %>)</small></td>
        <td><%= truncate(event.description, length: 100) %></td>
        <td><%= event.location %></td>
		<% if current_user.try(:admin) %>
        	<td><%= link_to 'Ändern', edit_event_path(event), class: "pure-button"  %></td>
        	<td><%= link_to 'Löschen', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "pure-button pure-button-warning" %></td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neues Event / neuen Workshop eintragen', new_event_path, class: "pure-button pure-button-primary" if current_user.try(:admin) %>

app/views/events/new.html.erb
<h1>Neuer Workshop</h1>

<%= render 'form' %>

<%= link_to 'Zurück', events_path %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<% unless @event.image_url.blank? %><p><%= image_tag @event.image_url %></p> <% end %>

<%= simple_format @event.description %>

<p>
  <strong>Timeslot:</strong>
  <%= @event.timeslot.name %><br>
  <%= l @event.timeslot.start_time, format: :short %> - <%= l @event.timeslot.end_time, format: :short %>
</p>

<p>
  <strong>Location:</strong>
  <%= link_to h(@event.location), (@event.location_url.blank? ? "http://www.google.de/maps?q=#{URI::escape(@event.location + ", Paderborn")}" : @event.location_url), target: "_blank" %>
</p>

<% if @reg %>

	<p style="color:green;">Du bist für diesen Workshop angemeldet. (Priorität <%= @reg.priority %>)</p>
	
	<%= button_to "Anmeldung stornieren", @reg, method: :delete, class: "pure-button pure-button-xsmall pure-button-warning" %>

<% else %>

	<%= form_for Registration.new, :html => { :class => "pure-form pure-form-aligned" } do |form| %>
		<%= form.hidden_field :event_id, value: @event.id %>
			<div class="pure-control-group"><label for="registration_priority">Priorität <i>(1=hoch)</i>:</label> <%= form.select :priority, @available_prios %></div>
			 <div class="pure-control-group"><%= form.submit "Für diesen Workshop anmelden!", class: "pure-button pure-button-primary" %></div>
	<% end %>

<% end %>

<% other_events = Event.where(timeslot_id: @event.timeslot.id).where.not(id: @event.id)
if other_events.any?
%>
<p><i>Andere Workshops während <%= @event.timeslot.name %>:</i></p>
<ul>
	<% other_events.each do |event| %>
		<li><%= link_to event.name, event %>
		<% if user_signed_in? && cur_reg = current_user.registrations.where(event_id: event.id).first %>
			<%= " (angemeldet, Prio " + cur_reg.priority.to_s + ")" %>
		<% end %>
		</li>
	<% end %>
</ul>
<% else %>
<p><i><small>Dies ist das einzige Event, was in diesem Timeslot stattfindet.</small></i></p>
<% end %>

<% if current_user.try(:admin) %><%= link_to 'Edit', edit_event_path(@event) %> |<% end %>
<%= link_to 'Zurück', events_path %>