config/routes.rb
ConferenceService::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "user_registrations"}
  resources :registrations, only: [:index, :create, :destroy]
  resources :speakers
  resources :events
  
  root 'events#index'
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConferenceService</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div class="content">
		<% if notice or alert %>
			<aside><%= notice %><%= alert %></aside>
		<% end %>
		
		<% if user_signed_in? && current_user.vegetarian.nil? %>
			<aside>Schön, dass du dich bei uns registriert hast!<br><b>&rArr; Bitte vervollständige noch ein paar <%= link_to "wichtige zusätzliche Infos", edit_user_registration_path, style: "color: white;" %>.</b> <br>Danach kannst du dir die Workshops anschauen und buchen.</aside>
		<% end %>
		
	    <div class="header">
	        <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
<!-- 	            <a class="pure-menu-heading" href="">Your Site</a> -->

	            <ul>
	                <li><%= link_to "Workshops", events_path %></li>
	                <% if user_signed_in? %>
					 <% if current_user.admin %>
					  <!-- <li><i><%= link_to "Anmeldungen/Buchungen", registrations_path %></li></i>
					  <li><i><%= link_to "Workshopleiter", speakers_path %></li></i> -->
					  <li><i><%= link_to "Teilnehmer/Admin", rails_admin.index_path('user') %></li></i>
					 <% end %>
					  <li><%= link_to "Meine Präferenzen und Daten", edit_user_registration_path %></li>
  					  <li><%= link_to current_user.firstname + " ausloggen", destroy_user_session_path, method: 'delete' %></li>
					<% else %>
					 <li><%= link_to "Registrieren", new_user_registration_path %></li>
					 <li><%= link_to "Einloggen", new_user_session_path %></li>
					<% end %>
	            </ul>
	        </div>
	    </div>
	</div>
	
	
	<div class="content">
		<%= yield %>
	</div>



</body>
</html>